# Generated by Django 5.2 on 2026-01-11 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('state_code', models.CharField(max_length=10)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=100)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_address', to='users.address')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('maiden_name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('image_url', models.URLField()),
                ('blood_group', models.CharField(max_length=5)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('eye_color', models.CharField(max_length=20)),
                ('hair_color', models.CharField(max_length=50)),
                ('hair_type', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=30)),
                ('crypto_wallet', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='users.address')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
            ],
        ),
    ]
