# Generated by Django 5.2 on 2026-01-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaluser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
