# Generated by Django 5.2 on 2026-01-28 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_address_lat_alter_address_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaluser',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='users.address'),
        ),
        migrations.AlterField(
            model_name='externaluser',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='users.company'),
        ),
    ]
