# Generated by Django 5.2 on 2026-01-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_externaluser_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaluser',
            name='image_url',
            field=models.URLField(),
        ),
    ]
