# Generated by Django 5.2 on 2026-01-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_product_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('total', models.FloatField()),
                ('discount_percentage', models.FloatField()),
                ('discounted_total', models.FloatField()),
                ('thumbnail', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(unique=True)),
                ('total', models.FloatField()),
                ('discounted_total', models.FloatField()),
                ('user_id', models.FloatField()),
                ('total_products', models.FloatField()),
                ('total_quantity', models.FloatField()),
                ('products', models.ManyToManyField(related_name='carts', to='carts.product')),
            ],
        ),
    ]
