# Generated by Django 5.2 on 2026-01-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_remove_externalcart_user_id_externalcart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discounted_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
