# Generated by Django 5.2 on 2026-01-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_alter_product_discounted_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalcart',
            name='discounted_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externalcart',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externalcart',
            name='total_products',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externalcart',
            name='total_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='external_product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
